/* ========================================
   AirGuard AI — Mock Data
   Sample datasets for all sections
   ======================================== */

const MOCK_DATA = {
    // ---- Hero Stats ----
    heroStats: [
        { value: 500, suffix: '+', label: 'Leaks Detected' },
        { value: 35, suffix: '%', label: 'Energy Saved' },
        { value: 2.4, suffix: 'M₹', label: 'Cost Savings' },
        { value: 120, suffix: 't', label: 'CO₂ Reduced' }
    ],

    // ---- Problem Statistics ----
    problems: [
        { icon: '💨', stat: '20-30%', title: 'Air Lost Through Leaks', desc: 'On average, 20-30% of compressed air generated by industrial compressors is lost through leaks, joints, and aging infrastructure.', color: 'danger' },
        { icon: '⚡', stat: '₹3.5L+', title: 'Increased Electricity Bills', desc: 'Compressed air leaks directly translate to wasted electricity, costing MSMEs lakhs of rupees annually in unnecessary energy consumption.', color: 'warning' },
        { icon: '⚙️', stat: '40%', title: 'Reduced Compressor Efficiency', desc: 'Leaks force compressors to work harder, reducing their efficiency by up to 40% and shortening their operational lifespan.', color: 'danger' },
        { icon: '🔧', stat: '2x', title: 'Higher Maintenance Costs', desc: 'Overworked compressors require more frequent maintenance, doubling repair costs and causing unexpected downtime.', color: 'warning' },
        { icon: '🌍', stat: '0.8%', title: 'Environmental Impact', desc: 'Industrial compressed air systems account for 0.8% of global electricity consumption. Leak reduction directly cuts carbon emissions.', color: 'danger' }
    ],

    // ---- Solution Steps ----
    solutionSteps: [
        { num: 1, icon: '📱', title: 'Open the Mobile App', desc: 'Launch AirGuard AI on your smartphone. No additional hardware or sensors needed — just your phone\'s built-in microphone.' },
        { num: 2, icon: '🔍', title: 'Scan the Compressor Area', desc: 'Walk around your compressor room and pipelines. The app listens for ultrasonic frequencies that indicate air leaks.' },
        { num: 3, icon: '🧠', title: 'AI Detects Ultrasonic Leak Sounds', desc: 'Our trained ML model analyzes the audio in real-time, filtering ambient noise and identifying leak signatures with 95%+ accuracy.' },
        { num: 4, icon: '📍', title: 'Leak Location is Highlighted', desc: 'The detected leak location is displayed on your screen with a clear visual indicator and confidence score.' },
        { num: 5, icon: '📊', title: 'Estimated Air Loss is Calculated', desc: 'AI estimates the volume of air being lost (in CFM), the severity of the leak, and the impact on compressor performance.' },
        { num: 6, icon: '💰', title: 'Annual Cost Savings Displayed', desc: 'See exactly how much money you\'ll save by fixing each leak, with projected annual energy savings in ₹ and kWh.' }
    ],

    // ---- AI Features ----
    aiFeatures: [
        { icon: '🔊', title: 'Ultrasonic Sound Analysis', desc: 'Captures and processes ultrasonic frequencies (20-100 kHz range) from your smartphone microphone to detect air leak signatures invisible to the human ear.' },
        { icon: '🤖', title: 'Machine Learning Classification', desc: 'Deep learning models trained on thousands of leak audio samples accurately classify leak types, sizes, and severity levels.' },
        { icon: '🔇', title: 'Advanced Noise Filtering', desc: 'Intelligent noise cancellation algorithms remove ambient factory sounds, isolating pure leak signals for accurate analysis.' },
        { icon: '⚡', title: 'Real-Time Leak Detection', desc: 'Process audio streams in real-time with sub-second latency, providing instant feedback as you scan your facility.' },
        { icon: '🔮', title: 'Predictive Maintenance', desc: 'AI predicts when leaks are likely to develop based on historical patterns, enabling proactive maintenance scheduling.' },
        { icon: '📈', title: 'Energy Analytics', desc: 'Comprehensive dashboards showing energy consumption patterns, cost trends, and optimization recommendations.' }
    ],

    // ---- Benefits ----
    benefits: [
        { icon: '💡', title: 'Reduce Electricity Bills', desc: 'Cut energy costs by up to 35% by identifying and fixing compressed air leaks across your facility.', color: 'blue' },
        { icon: '⚙️', title: 'Improve Compressor Efficiency', desc: 'Optimize compressor performance by eliminating leaks that force equipment to work harder than necessary.', color: 'green' },
        { icon: '🔧', title: 'Lower Maintenance Costs', desc: 'Reduce wear and tear on compressors, extending equipment lifespan and cutting maintenance expenses by 50%.', color: 'blue' },
        { icon: '🌱', title: 'Reduce Carbon Emissions', desc: 'Lower your facility\'s carbon footprint by minimizing wasted energy from compressed air leaks.', color: 'green' },
        { icon: '⏱️', title: 'Increase Equipment Lifespan', desc: 'Properly maintained compressors last 2-3x longer, maximizing your capital investment.', color: 'blue' },
        { icon: '📱', title: 'Phone-Based Solution', desc: 'No expensive equipment needed. Just use your existing smartphone to detect leaks anywhere in your facility.', color: 'green' },
        { icon: '💰', title: 'Affordable for MSMEs', desc: 'Designed with small and medium enterprises in mind. Enterprise-grade leak detection at a fraction of the cost.', color: 'blue' }
    ],

    // ---- Tech Stack ----
    techStack: [
        { icon: '⚛️', name: 'React', desc: 'Frontend UI', color: '#61DAFB' },
        { icon: '🎨', name: 'Tailwind CSS', desc: 'Styling', color: '#06B6D4' },
        { icon: '🟢', name: 'Node.js', desc: 'Backend Runtime', color: '#339933' },
        { icon: '🐍', name: 'Python', desc: 'AI/ML Engine', color: '#3776AB' },
        { icon: '🧠', name: 'TensorFlow', desc: 'Deep Learning', color: '#FF6F00' },
        { icon: '🚀', name: 'FastAPI', desc: 'API Server', color: '#009688' },
        { icon: '🔥', name: 'Firebase', desc: 'Auth & Hosting', color: '#FFCA28' },
        { icon: '🍃', name: 'MongoDB', desc: 'Database', color: '#47A248' },
        { icon: '📊', name: 'Chart.js', desc: 'Data Visualization', color: '#FF6384' },
        { icon: '🎵', name: 'Web Audio API', desc: 'Audio Processing', color: '#9C27B0' }
    ],

    // ---- Dashboard KPIs ----
    dashboardKPIs: [
        { icon: '🔍', label: 'Total Leaks Detected', value: 47, change: '+12', positive: true, bg: 'rgba(37, 99, 235, 0.1)', color: 'var(--blue-500)' },
        { icon: '⚡', label: 'Energy Saved (kWh)', value: 12450, change: '+8.3%', positive: true, bg: 'rgba(16, 185, 129, 0.1)', color: 'var(--green-500)' },
        { icon: '💰', label: 'Monthly Savings (₹)', value: 84200, change: '+15.7%', positive: true, bg: 'rgba(245, 158, 11, 0.1)', color: 'var(--warning)' },
        { icon: '🌿', label: 'CO₂ Reduced (kg)', value: 3820, change: '+11.2%', positive: true, bg: 'rgba(16, 185, 129, 0.1)', color: 'var(--green-500)' }
    ],

    // ---- Dashboard Charts Data ----
    monthlySavings: [
        { month: 'Jan', savings: 42000 },
        { month: 'Feb', savings: 48000 },
        { month: 'Mar', savings: 55000 },
        { month: 'Apr', savings: 61000 },
        { month: 'May', savings: 58000 },
        { month: 'Jun', savings: 72000 },
        { month: 'Jul', savings: 84200 }
    ],

    leakSeverity: [
        { label: 'Low', value: 18, color: '#10B981' },
        { label: 'Medium', value: 21, color: '#F59E0B' },
        { label: 'High', value: 8, color: '#EF4444' }
    ],

    energyTrend: [
        { month: 'Jan', consumed: 4200, saved: 1200 },
        { month: 'Feb', consumed: 4100, saved: 1450 },
        { month: 'Mar', consumed: 3900, saved: 1800 },
        { month: 'Apr', consumed: 3700, saved: 2100 },
        { month: 'May', consumed: 3800, saved: 1950 },
        { month: 'Jun', consumed: 3500, saved: 2400 },
        { month: 'Jul', consumed: 3300, saved: 2650 }
    ],

    leakHistory: [
        { id: 'LK-047', date: '2026-07-10', location: 'Compressor Room A', severity: 'High', airLoss: '12.5 CFM', cost: '₹8,400/mo', status: 'Open' },
        { id: 'LK-046', date: '2026-07-08', location: 'Pipeline B-3', severity: 'Medium', airLoss: '6.2 CFM', cost: '₹4,100/mo', status: 'Fixing' },
        { id: 'LK-045', date: '2026-07-05', location: 'Valve Joint C-7', severity: 'Low', airLoss: '2.1 CFM', cost: '₹1,400/mo', status: 'Fixed' },
        { id: 'LK-044', date: '2026-07-03', location: 'Dryer Unit D', severity: 'High', airLoss: '15.8 CFM', cost: '₹10,600/mo', status: 'Fixed' },
        { id: 'LK-043', date: '2026-06-28', location: 'Compressor Room B', severity: 'Medium', airLoss: '7.4 CFM', cost: '₹4,900/mo', status: 'Fixed' },
        { id: 'LK-042', date: '2026-06-25', location: 'Main Supply Line', severity: 'Low', airLoss: '3.3 CFM', cost: '₹2,200/mo', status: 'Fixed' }
    ],

    heatmapLeaks: [
        { x: 15, y: 25, severity: 'high', label: 'Compressor A' },
        { x: 35, y: 45, severity: 'medium', label: 'Pipeline B' },
        { x: 55, y: 30, severity: 'low', label: 'Valve C' },
        { x: 72, y: 60, severity: 'high', label: 'Dryer D' },
        { x: 25, y: 70, severity: 'medium', label: 'Junction E' },
        { x: 85, y: 35, severity: 'low', label: 'Filter F' },
        { x: 48, y: 75, severity: 'medium', label: 'Outlet G' }
    ],

    // ---- Compressor Health ----
    compressorHealth: 78,

    // ---- Testimonials ----
    testimonials: [
        { text: 'AirGuard AI helped us identify 23 leaks in our facility that we didn\'t even know existed. We\'re saving ₹1.2 lakh per month on electricity alone!', name: 'Rajesh Kumar', role: 'Plant Manager, AutoParts Mfg', avatar: 'RK' },
        { text: 'The phone-based detection is a game-changer. No expensive equipment needed — our maintenance team just walks around with their phones and finds leaks instantly.', name: 'Priya Sharma', role: 'Operations Head, TechFab Industries', avatar: 'PS' },
        { text: 'We reduced our compressed air energy costs by 28% in the first month. The ROI was immediate and the AI accuracy is impressive.', name: 'Anil Mehta', role: 'Factory Owner, Mehta Engineering', avatar: 'AM' },
        { text: 'The dashboard analytics give us insights we never had before. Predictive maintenance alerts have prevented 3 major breakdowns this quarter.', name: 'Sunita Patel', role: 'Maintenance Lead, GreenTech Solutions', avatar: 'SP' }
    ],

    // ---- FAQ ----
    faq: [
        { q: 'How does AirGuard AI detect leaks using a smartphone?', a: 'AirGuard AI uses your phone\'s microphone to capture ultrasonic frequencies emitted by compressed air leaks. Our AI model, trained on thousands of leak samples, analyzes the audio in real-time and identifies leak signatures with over 95% accuracy.' },
        { q: 'Do I need any special hardware or sensors?', a: 'No! AirGuard AI works with your existing smartphone. No additional hardware, sensors, or expensive ultrasonic detectors are needed. Just download the app and start scanning.' },
        { q: 'How accurate is the leak detection?', a: 'Our AI model achieves 95.6% accuracy in lab conditions and 92.3% in real-world industrial environments. The model continuously improves as more data is collected.' },
        { q: 'What types of leaks can be detected?', a: 'AirGuard AI can detect leaks in compressors, pipelines, valves, fittings, hose connections, dryers, filters, and other compressed air system components.' },
        { q: 'How much money can I save?', a: 'On average, our clients save ₹50,000 to ₹5,00,000 per month depending on facility size and number of leaks detected. Most see ROI within the first week.' },
        { q: 'Is there a free trial available?', a: 'Yes! We offer a 14-day free trial with full access to all features. No credit card required. Contact us to get started.' },
        { q: 'Can it work in noisy factory environments?', a: 'Absolutely. Our advanced noise filtering algorithms are specifically designed for industrial environments. The AI separates leak sounds from ambient factory noise with high precision.' },
        { q: 'Do you provide reports and analytics?', a: 'Yes, AirGuard AI provides comprehensive dashboards with leak history, energy analytics, cost savings tracking, predictive maintenance alerts, and downloadable PDF reports.' }
    ],

    // ---- Blog Posts ----
    blogPosts: [
        { id: 1, title: 'How AI is Revolutionizing Compressed Air Leak Detection', date: 'July 8, 2026', category: 'Technology', excerpt: 'Traditional leak detection methods are expensive and time-consuming. Learn how AI-powered ultrasonic analysis is changing the game for Indian MSMEs.', icon: '🤖', readTime: '5 min' },
        { id: 2, title: '5 Signs Your Compressor System Has Air Leaks', date: 'July 2, 2026', category: 'Maintenance', excerpt: 'Unexpected energy bills? Compressor running non-stop? Here are the top warning signs of compressed air leaks and what to do about them.', icon: '🔧', readTime: '4 min' },
        { id: 3, title: 'The True Cost of Compressed Air Leaks in Indian Factories', date: 'June 25, 2026', category: 'Industry', excerpt: 'A deep dive into the financial impact of air leaks on Indian manufacturing. Spoiler: it\'s costing you more than you think.', icon: '💰', readTime: '6 min' },
        { id: 4, title: 'Phone-Based Ultrasonic Detection: The Science Behind It', date: 'June 18, 2026', category: 'Research', excerpt: 'How modern smartphones can capture ultrasonic frequencies and how machine learning turns raw audio into actionable leak reports.', icon: '📱', readTime: '7 min' },
        { id: 5, title: 'Predictive Maintenance: Preventing Leaks Before They Happen', date: 'June 10, 2026', category: 'AI', excerpt: 'Explore how AirGuard AI uses historical data patterns to predict when and where leaks are likely to develop in your facility.', icon: '🔮', readTime: '5 min' },
        { id: 6, title: 'Case Study: AutoParts Mfg Saves ₹14L Annually', date: 'June 3, 2026', category: 'Case Study', excerpt: 'How a medium-sized auto parts manufacturer in Pune identified 23 leaks and reduced energy costs by 28% using AirGuard AI.', icon: '📋', readTime: '4 min' }
    ],

    // ---- Team ----
    team: [
        { name: 'Dr. Arjun Rao', role: 'CEO & AI Lead', bio: 'PhD in Signal Processing, IIT Bombay. 10+ years in industrial IoT.', avatar: '👨‍💼' },
        { name: 'Neha Kapoor', role: 'CTO', bio: 'Ex-Google engineer. Expert in ML deployment and edge computing.', avatar: '👩‍💻' },
        { name: 'Vikram Singh', role: 'Product Lead', bio: 'Former McKinsey consultant. Passionate about MSME digital transformation.', avatar: '👨‍💻' },
        { name: 'Isha Gupta', role: 'Data Scientist', bio: 'M.Tech AI, IISC Bangalore. Specialist in audio ML and noise filtering.', avatar: '👩‍🔬' }
    ],

    // ---- About Values ----
    values: [
        { icon: '🎯', title: 'Innovation', desc: 'Pushing the boundaries of what\'s possible with smartphone-based industrial AI.' },
        { icon: '🤝', title: 'Accessibility', desc: 'Making enterprise-grade technology affordable and accessible to every MSME.' },
        { icon: '🌍', title: 'Sustainability', desc: 'Committed to reducing industrial energy waste and carbon emissions.' }
    ],

    // ---- Demo AI Results (mock) ----
    generateDemoResults: function() {
        const confidence = (85 + Math.random() * 14).toFixed(1);
        const severity = confidence > 93 ? 'High' : confidence > 88 ? 'Medium' : 'Low';
        const noiseLevel = (45 + Math.random() * 35).toFixed(1);
        const leakSize = severity === 'High' ? (8 + Math.random() * 10).toFixed(1) : severity === 'Medium' ? (3 + Math.random() * 5).toFixed(1) : (0.5 + Math.random() * 3).toFixed(1);
        const energyLoss = (parseFloat(leakSize) * 450 + Math.random() * 200).toFixed(0);
        const costLoss = (parseFloat(energyLoss) * 8.5).toFixed(0);
        const probability = (parseFloat(confidence) - 2 + Math.random() * 4).toFixed(1);

        return {
            confidence: parseFloat(confidence),
            probability: Math.min(99, parseFloat(probability)),
            severity,
            noiseLevel: parseFloat(noiseLevel),
            leakSize: parseFloat(leakSize),
            energyLoss: parseInt(energyLoss),
            costLoss: parseInt(costLoss),
            maintenance: [
                'Inspect and tighten all fittings in detected area',
                'Replace worn gaskets and seals',
                'Apply thread sealant to pipe connections',
                'Schedule ultrasonic re-scan after repairs',
                'Document leak location for maintenance records',
                severity === 'High' ? 'URGENT: Isolate section and repair immediately' : 'Schedule repair within 1-2 weeks'
            ]
        };
    }
};
